<?php
/**
 * @package App Utils
 * @subpackage Collections
 * @see \AppUtils\Traits\StringPrimaryCollectionTrait
 */

declare(strict_types=1);

namespace AppUtils\Traits;

use AppUtils\Collections\CollectionException;
use AppUtils\Collections\Events\ItemsInitializedEvent;
use AppUtils\Collections\RecordNotExistsException;
use AppUtils\Interfaces\CollectionRecordInterface;
use AppUtils\Interfaces\StringPrimaryCollectionInterface;
use AppUtils\Interfaces\StringPrimaryRecordInterface;

/**
 * Trait that can be used to implement a string-based item collection
 * without extending the {@see BaseStringPrimaryCollection} class - for
 * example, if the class already extends another class.
 *
 * @package App Utils
 * @subpackage Collections
 * @author Sebastian Mordziol <s.mordziol@mistralys.eu>
 * @auto-generated This trait was generated by the {@see \AppUtils\Collections\Build\TraitBuilder::build()} command @2025-07-25 09:10:36
 *
 * @see StringPrimaryCollectionInterface
 */
trait StringPrimaryCollectionTrait
{
    /**
     * @var array<string,StringPrimaryRecordInterface>|NULL
     */
    protected ?array $items = null;

    /**
     * @return array<string,StringPrimaryRecordInterface>
     */
    protected function initItems() : array
    {
        if($this->items !== null) {
            return $this->items;
        }

        $this->items = array();

        $this->registerItems();
        $this->doSort();

        $this->triggerEvent(new ItemsInitializedEvent($this));

        // PHPStan does not understand that the items are initialized at this point.
        return $this->items ?? array();
    }

    /**
     * @return $this
     */
    protected function doSort() : self
    {
        if(isset($this->items)) {
            uasort($this->items, array($this, 'sortItems'));
        }

        return $this;
    }

    protected function isInitialized() : bool
    {
        return isset($this->items);
    }

    /**
     * Resets the collection, clearing all items.
     * @return void
     */
    protected function reset() : void
    {
        $this->items = null;
    }

    protected function sortItems(StringPrimaryRecordInterface $a, StringPrimaryRecordInterface $b) : int
    {
        return strnatcasecmp($a->getID(), $b->getID());
    }

    abstract protected function registerItems() : void;

    /**
     * Registers an item in the collection.
     *
     * > NOTE: Use {@see self::tryRegisterItem()} if you want to check
     * > whether the item was successfully registered or not.
     *
     * @param CollectionRecordInterface $item
     * @return $this
     */
    protected function registerItem(CollectionRecordInterface $item) : self
    {
        $this->tryRegisterItem($item);
        return $this;
    }

    /**
     * Registers an item in the collection if it is of the expected type
     * and not already present in the collection.
     *
     * @param CollectionRecordInterface $item
     * @return bool Whether the item was successfully registered.
     */
    protected function tryRegisterItem(CollectionRecordInterface $item) : bool
    {
        if($item instanceof StringPrimaryRecordInterface && !isset($this->items[$item->getID()])) {
            $this->items[$item->getID()] = $item;
            return true;
        }

        return false;
    }

    /**
     * @return StringPrimaryRecordInterface[]
     */
    public function getAll() : array
    {
        return array_values($this->initItems());
    }

    /**
     * @return StringPrimaryRecordInterface
     * @throws CollectionException
     */
    public function getDefault(): StringPrimaryRecordInterface
    {
        return $this->getByID($this->getDefaultID());
    }

    /**
     * @param string $id
     * @return StringPrimaryRecordInterface
     * @throws CollectionException
     */
    public function getByID(string $id) : StringPrimaryRecordInterface
    {
        $items = $this->initItems();

        if(isset($items[$id]))
        {
            return $items[$id];
        }

        throw new RecordNotExistsException($this, $id, StringPrimaryCollectionInterface::ERROR_CODE_RECORD_NOT_FOUND);
    }

    public function idExists(string $id) : bool
    {
        $items = $this->initItems();

        return isset($items[$id]);
    }

    public function getIDs(): array
    {
        return array_keys($this->initItems());
    }

    /**
     * Utility method that can be used in the {@see self::getDefaultID()}
     * method if no specific default ID is available. Will automatically
     * use the first item in the collection as the default ID if the
     * list is not empty.
     *
     * @return string
     */
    protected function getAutoDefault() : string
    {
        // Important: Init the items here to ensure that the
        // collection is loaded and sorted before we try to
        // access the first item.
        $items = $this->initItems();

        if(!empty($items)) {
            return array_key_first($items);
        }

        return StringPrimaryCollectionInterface::ID_NO_DEFAULT_AVAILABLE;
    }
}
